### PR TITLE
feat: only allow many

### PR DESCRIPTION
**Pull request by rharkor**
I've integrated the possiblity of use of many package managers

### CODE REVIEW

**Comment by zkochan** [comment]
It is a terrible idea to allow multiple package managers.

**Comment by rharkor** [comment]
> It is a terrible idea to allow multiple package managers.

Why is it ?
Imagine you take bun & yarn, they have different .lock files so I don't really understand the problem..

**Comment by jariz** [comment]
@rharkor that will ruin the entire point of the lockfiles

**Comment by rharkor** [comment]
@jariz, yes when I made this one year ago I was thinking of using bun and npm because it use the same lock file but that's a really bad idea, I have forgotten this pr, I will close it ty 😉

**Pull request closed without merging**
