### PR TITLE
feat: :sparkles: It'll bring significant growth for npm download, because chinese users love new things to applied

### PR DESCRIPTION
**Pull request by luckymore**
1. add `cnpm` to wantedPM list(actually is `npminstall` when run `cnpm install`)
2. support pacakge manager `version` detect

### CODE REVIEW

**Comment by zkochan** [comment]
I think we can make an update to `which-pm-runs` https://github.com/zkochan/packages/tree/main/which-pm-runs
so that it detects `npminstall` and returns `cnpm`

**Comment by luckymore** [comment]
@zkochan cool，how about the `version detect` feature

**Comment by sorrycc** [comment]
[which-pm-runs](https://github.com/zkochan/packages/tree/main/which-pm-runs)@1.1.0 breaks husky@4+cnpm hang up, ref: https://github.com/cnpm/bug-versions/pull/174

**Comment by zkochan** [comment]
so it should be fixed in Husky, right?

**Comment by zkochan** [comment]
why do you change the name of the package?

**Comment by jimmyko** [comment]
I don't think this PR should be kept since it looks like a fork rather than adding a new feature.

**Comment by skyclouds2001** [comment]
个人认为，如果无意认真贡献的话，就不要贡献了

**Comment by luckymore** [comment]
sorry about that... 我都提了些什么鬼，乌龙

**Pull request closed without merging**
